### ISSUE TITLE
an example

### ISSUE THREAD

**Issue by sonwh98** [idiotslowdown/famous-cljs#1]
Thanks for working on this.  Do you have a hello world example?

**Comment by idiotslowdown** [comment]
I will get something up today

**Comment by idiotslowdown** [comment]
I put the starter-kit default example up...I think building on that can get you pretty far. Using surfaces and modifiers etc is pretty easy, but unfortunately the docs for the physics stuff  is basically non-existent atm. Ive been meaning to shoot them an angry email for a couple weeks now
